AWSTemplateFormatVersion: 2010-09-09
Description: Main stack for the event-driven data platform

Parameters:
  TemplatesBucket:
    Type: String
    Default: data-platform-event-driven-project
    Description: S3 bucket where CFN templates are stored

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/cfn/vpc.yaml"

  IAMStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub "https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/cfn/iam_role.yaml"

  S3Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !Sub "https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/cfn/s3.yaml"

  SecretsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !Sub "https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/cfn/secrets_manager.yaml"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - S3Stack
      - SecretsStack
    Properties:
      TemplateURL: !Sub "https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/cfn/lambda.yaml"

  RedshiftStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMStack
      - SecretsStack
    Properties:
      TemplateURL: !Sub "https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/cfn/redshift.yaml"

  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
      - RedshiftStack
    Properties:
      TemplateURL: !Sub "https://${TemplatesBucket}.s3.${AWS::Region}.amazonaws.com/cfn/monitoring.yaml"